name: pacman graph

on:
  schedule: # Run automatically every 24 hours
    - cron: "0 */24 * * *"
  workflow_dispatch: # Allows manual triggering
  push: # Runs on every push to the main branch
    branches:
      - main
  pull_request: # Runs on every push to a pull request
    types: [opened, synchronize, reopened]

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: generate-pacman-game-from-github-contribution-grid
        uses: abozanona/pacman-contribution-grid@1.0.10.2